# Tratamento e Análise dados Betano

In [2]:
#IMPORTANDO AS BIBLIOTECAS NECESSÃRIAS
import pandas as pd

In [23]:
# CARREGANDO DATA DO CSV
df_ba = pd.read_csv('dados/jogos_betanoBrasil.csv', on_bad_lines='skip') # PULA LINHAS MAL FORMATADAS

## Tratamento dos dados
- Renomear as colunas
- Eliminar colunas inuteis
- Tratamento dos nulos
- Ajuste dos tipos

In [24]:
# Renomeando as colunas
df_ba.columns = ['data', 'hora', 'time_casa', 'time_visitante',
                 'resultado final', 'casa_ganha', 'empate', 'visitante_ganha',
                 'total_mais/menos', '+', 'maisq', '-', 'menosq', 'ambasmarcam',
                 'sim', 'simodd', 'não', 'nãoodd', 'dejn']
df_ba

,data,hora,time_casa,time_visitante,resultado final,casa_ganha,empate,visitante_ganha,total_mais/menos,+,maisq,-,menosq,ambasmarcam,sim,simodd,não,nãoodd,dejn
0,30/01,22:00,Club Atletico Tucuman II,Boca Juniors II,Resultado Final,3.90,3.50,1.82,Total de Gols Mais/Menos,+,1.98,-,1.65,Ambas equipes Marcam,Sim,1.88,Não,1.72,31.0
1,30/01,22:00,CF Tigres UANL (F),Deportivo Toluca FC (F),Resultado Final,1.07,10.00,14.50,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,30/01,22:10,Once Caldas,Deportes Tolima,Resultado Final,2.32,2.92,3.60,Total de Gols Mais/Menos,+,2.70,-,1.47,Ambas equipes Marcam,Sim,2.15,Não,1.65,271.0
3,31/01,00:00,Mazatlán FC (F),Cruz Azul (F),Resultado Final,6.50,4.75,1.36,Total de Gols Mais/Menos,+,1.52,-,2.20,16,NaN,NaN,NaN,NaN,NaN
4,31/01,00:05,Guadalajara Chivas (F),Juarez (F),Resultado Final,1.42,4.70,5.50,Total de Gols Mais/Menos,+,1.60,-,2.05,16,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,31/01,16:45,Tadcaster Albion,Sheffield FC,Resultado Final,4.60,3.90,1.60,Total de Gols Mais/Menos,+,1.53,-,2.18,16,NaN,NaN,NaN,NaN,NaN
306,31/01,16:45,Cirencester Town,Barton Rovers,Resultado Final,1.26,5.40,8.25,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,31/01,16:45,Maldon & Tiptree FC,Wroxham,Resultado Final,2.12,3.45,2.92,Total de Gols Mais/Menos,+,1.62,-,2.02,16,NaN,NaN,NaN,NaN,NaN
308,31/01,16:45,Chichester City Utd,Lancing FC,Resultado Final,2.20,3.20,3.00,Total de Gols Mais/Menos,+,1.65,-,2.00,16,NaN,NaN,NaN,NaN,NaN
309,31/01,16:00,Arsenal Sub-21,Burnley Sub-21,Resultado Final,2.02,3.90,2.95,Total de Gols Mais/Menos,+,1.32,-,2.85,Ambas equipes Marcam,Sim,1.31,Não,2.87,35.0

In [25]:
# Eliminando as colunas inuteis
df_ba.drop(['total_mais/menos', '+', '-','resultado final', 'ambasmarcam', 'sim', 'não', 'dejn'], axis='columns', inplace=True)

In [26]:
df_ba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data             298 non-null    object
 1   hora             298 non-null    object
 2   time_casa        298 non-null    object
 3   time_visitante   298 non-null    object
 4   casa_ganha       298 non-null    float64
 5   empate           298 non-null    float64
 6   visitante_ganha  298 non-null    float64
 7   maisq            293 non-null    float64
 8   menosq           293 non-null    float64
 9   simodd           282 non-null    float64
 10  nãoodd           282 non-null    float64
dtypes: float64(7), object(4)
memory usage: 26.8+ KB

In [27]:
# Tratando os nulos
# REMOVENDO TODAS AS COLUNAS QUE POSSUEM APENAS VALORES NULOS
df_semNulo = df_ba.dropna(axis='rows') # type: ignore

In [29]:
df_semNulo.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 282 entries, 0 to 309
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data             282 non-null    object
 1   hora             282 non-null    object
 2   time_casa        282 non-null    object
 3   time_visitante   282 non-null    object
 4   casa_ganha       282 non-null    float64
 5   empate           282 non-null    float64
 6   visitante_ganha  282 non-null    float64
 7   maisq            282 non-null    float64
 8   menosq           282 non-null    float64
 9   simodd           282 non-null    float64
 10  nãoodd           282 non-null    float64
dtypes: float64(7), object(4)
memory usage: 26.4+ KB

In [31]:
df_semNulo['data'] = pd.to_datetime(df_semNulo['data'], format='%d/%m')

C:\Users\lucad\AppData\Local\Temp\ipykernel_28968\3036133766.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_semNulo['data'] = pd.to_datetime(df_semNulo['data'], format='%d/%m')

In [33]:
df_semNulo.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 282 entries, 0 to 309
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data             282 non-null    datetime64[ns]
 1   hora             282 non-null    object
 2   time_casa        282 non-null    object
 3   time_visitante   282 non-null    object
 4   casa_ganha       282 non-null    float64
 5   empate           282 non-null    float64
 6   visitante_ganha  282 non-null    float64
 7   maisq            282 non-null    float64
 8   menosq           282 non-null    float64
 9   simodd           282 non-null    float64
 10  nãoodd           282 non-null    float64
dtypes: datetime64[ns](1), float64(7), object(3)
memory usage: 26.4+ KB

## Analise dos dados
- Buscando outliers
- Verificando as distribuições
- Buscar relações entre variaveis